spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mariadb://127.0.0.1:3306/app_2022_09_23?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
logging:
  level:
    com.ll.exam.app_2022_09_23: debug
